export const products = [
    {
        id: 1,
        product:"Adi2000",
        brand:"ADIDAS",
        size:"38(ARG) - 8(US)",
        category:"arrivals",
        description: "Zapatillas urbanas que se adaptan a cualquier estilo, te mantienen en contacto con la naturaleza incorporando materiales reciclados y a la vez, su estilo renovando de la década de los 90, te entrega un look insuperable. La entresuela de espuma y la suela tipo Wafle, combina con corcho y goma para darte mejor tracción a la hora de recorrer la ciudad. Se incorpora la unidad AirMax visible que amortigua cada paso dándote una experiencia única sin importar donde vayas. Este calzado se convirtió en un must de esta temporada y encaja perfecto en cualquier plan super casual, o elegante sport. Si todavía no las tenés, estás perdiendote muchos planes."  ,
        price:32000,
        stock:2,
        sale: "no",
        image: "https://www.kickz.com/dw/image/v2/BGQV_PRD/on/demandware.static/-/Sites-kickz-master-catalog/default/dwb93c58d0/images/large/adidas_originals-ADI2000_Womens-CWHITE_CBLACK_FTWWHT-2.jpg?sw=537&q=95",
    },
    {
        id: 2,
        product:"Bad Bunny Forum Low Pink (Easter Egg) -Replica-",
        brand:"ADIDAS",
        size:"40 (ARG) 8.5(US)",
        category:"men",
        description: "Zapatillas urbanas que se adaptan a cualquier estilo, te mantienen en contacto con la naturaleza incorporando materiales reciclados y a la vez, su estilo renovando de la década de los 90, te entrega un look insuperable. La entresuela de espuma y la suela tipo Wafle, combina con corcho y goma para darte mejor tracción a la hora de recorrer la ciudad. Se incorpora la unidad AirMax visible que amortigua cada paso dándote una experiencia única sin importar donde vayas. Este calzado se convirtió en un must de esta temporada y encaja perfecto en cualquier plan super casual, o elegante sport. Si todavía no las tenés, estás perdiendote muchos planes." ,
        price:25000,
        stock:2,
        sale: "si",
        image: "https://exclusiveshopperu.com/wp-content/uploads/adidas-Forum-Low-Bad-Bunny-Pink-Easter-Egg.jpg",
    },
    {
        id: 3,
        product:"Court Graffik",
        brand:"DC Shoes",
        size:"42(ARG) - 9.5(US) ",
        category:"arrivals",
        description: "Zapatillas urbanas que se adaptan a cualquier estilo, te mantienen en contacto con la naturaleza incorporando materiales reciclados y a la vez, su estilo renovando de la década de los 90, te entrega un look insuperable. La entresuela de espuma y la suela tipo Wafle, combina con corcho y goma para darte mejor tracción a la hora de recorrer la ciudad. Se incorpora la unidad AirMax visible que amortigua cada paso dándote una experiencia única sin importar donde vayas. Este calzado se convirtió en un must de esta temporada y encaja perfecto en cualquier plan super casual, o elegante sport. Si todavía no las tenés, estás perdiendote muchos planes."  ,
        price: 23000,
        stock:3,
        sale: "si",
        image: "https://www.tradeinn.com/f/13608/136081081/dc-shoes-zapatillas-court-graffik.jpg",
    },
    {
        id: 4,
        product:"550 woman",
        brand:"NEW BALANCE",
        size:"37 (ARG) - 7.5 (US)",
        category:"women",
        description: "Zapatillas urbanas que se adaptan a cualquier estilo, te mantienen en contacto con la naturaleza incorporando materiales reciclados y a la vez, su estilo renovando de la década de los 90, te entrega un look insuperable. La entresuela de espuma y la suela tipo Wafle, combina con corcho y goma para darte mejor tracción a la hora de recorrer la ciudad. Se incorpora la unidad AirMax visible que amortigua cada paso dándote una experiencia única sin importar donde vayas. Este calzado se convirtió en un must de esta temporada y encaja perfecto en cualquier plan super casual, o elegante sport. Si todavía no las tenés, estás perdiendote muchos planes."  ,
        price:22.000,
        stock:4,
        sale: "no",
        image: "https://www.kicksonfire.com/wp-content/uploads/2022/08/bbw550wp-nb-05-i.jpg?x58464",
    },
    {
        id: 5,
        product:"DUNK Low Court Cheetah",
        brand:"NIKE",
        size:"41 (ARG) - 9 (US)",
        category:"men",
        description: "Zapatillas urbanas que se adaptan a cualquier estilo, te mantienen en contacto con la naturaleza incorporando materiales reciclados y a la vez, su estilo renovando de la década de los 90, te entrega un look insuperable. La entresuela de espuma y la suela tipo Wafle, combina con corcho y goma para darte mejor tracción a la hora de recorrer la ciudad. Se incorpora la unidad AirMax visible que amortigua cada paso dándote una experiencia única sin importar donde vayas. Este calzado se convirtió en un must de esta temporada y encaja perfecto en cualquier plan super casual, o elegante sport. Si todavía no las tenés, estás perdiendote muchos planes."  ,
        price:27000,
        stock:4,
        sale: "no" ,
        image: "https://cdn.sneaktorious.com/_Resources/Persistent/c/5/0/d/c50d545ce4428b731d8bc7acb837228cb364cd0d/Nike-Dunk-Low-Retro-PRM-Animal-Pack-DH7913-200-Release-Date-Raffle-List--600x600.jpg",
    },
    {
        id: 6,
        product:"DUNK Low Court DISRUPT 2",
        brand:"NIKE",
        size:"43 (ARG) - 10.5 (US)",
        category:"men",
        description: "Zapatillas urbanas que se adaptan a cualquier estilo, te mantienen en contacto con la naturaleza incorporando materiales reciclados y a la vez, su estilo renovando de la década de los 90, te entrega un look insuperable. La entresuela de espuma y la suela tipo Wafle, combina con corcho y goma para darte mejor tracción a la hora de recorrer la ciudad. Se incorpora la unidad AirMax visible que amortigua cada paso dándote una experiencia única sin importar donde vayas. Este calzado se convirtió en un must de esta temporada y encaja perfecto en cualquier plan super casual, o elegante sport. Si todavía no las tenés, estás perdiendote muchos planes."  ,
        price: 29000,
        stock:1,
        sale: "no",
        image: "https://essential.vtexassets.com/arquivos/ids/580272-800-auto?v=637924808241670000&width=800&height=auto&aspect=true",
    },
    {
        id: 7,
        product:"DUNK Low Court TRUCK IT",
        brand:"NIKE",
        size:"42 (ARG) - 10.5 (US)",
        category:"men",
        description:"Zapatillas urbanas que se adaptan a cualquier estilo, te mantienen en contacto con la naturaleza incorporando materiales reciclados y a la vez, su estilo renovando de la década de los 90, te entrega un look insuperable. La entresuela de espuma y la suela tipo Wafle, combina con corcho y goma para darte mejor tracción a la hora de recorrer la ciudad. Se incorpora la unidad AirMax visible que amortigua cada paso dándote una experiencia única sin importar donde vayas. Este calzado se convirtió en un must de esta temporada y encaja perfecto en cualquier plan super casual, o elegante sport. Si todavía no las tenés, estás perdiendote muchos planes." ,
        price:32000,
        stock:4,
        sale: "no",
        image: "https://media.endclothing.com/media/catalog/product/2/5/25-01-2020_nike_sbdunklo_cream_royal_blue_ct6688-200_blr_1.jpg",
    },
    {
        id: 8,
        product:"KOSMO RIDER ",
        brand:"PUMA",
        size:"37.5 (ARG) - 7.5(US)",
        category:"women",
        description: "Zapatillas urbanas que se adaptan a cualquier estilo, te mantienen en contacto con la naturaleza incorporando materiales reciclados y a la vez, su estilo renovando de la década de los 90, te entrega un look insuperable. La entresuela de espuma y la suela tipo Wafle, combina con corcho y goma para darte mejor tracción a la hora de recorrer la ciudad. Se incorpora la unidad AirMax visible que amortigua cada paso dándote una experiencia única sin importar donde vayas. Este calzado se convirtió en un must de esta temporada y encaja perfecto en cualquier plan super casual, o elegante sport. Si todavía no las tenés, estás perdiendote muchos planes."  ,
        price:24000,
        stock:3,
        sale: "no",
        image: "https://essential.vtexassets.com/arquivos/ids/591494-800-auto?v=637937756421670000&width=800&height=auto&aspect=true",
    },
    
]